### ISSUE TITLE
DHTML menu and umlauts

### ISSUE THREAD

**Issue by Finkregh** [dottedmag/archmage#5] opened 2015-04-14 09:31 UTC
the DHTML menu in the left frame does not properly encode special characters (e.g. umlauts: `EinfÃ¼hrung` instead of `Einführung`)

**Comment by dottedmag** [comment] 2015-04-19 13:40
Could you please attach a file to reproduce this issue?

**Comment by dottedmag** [comment] 2015-10-06 06:32
Closing, unable to reproduce without the document in question.

**Closed as completed by dottedmag** 2015-10-06 06:32 UTC
